# Tensors [link](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

Tensors share the smae properties with numpy indexing, ...

In [1]:
import torch
import numpy as np

/home/abdullah/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Initializing Tensors

In [2]:
# from data

data = [[1, 2],
        [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
#from numpy 
np_array = np.array(data)
x_p = torch.from_numpy(np_array)
x_p

tensor([[1, 2],
        [3, 4]])

In [4]:
# From another tensor

#returun a tensor with same proprties (i.e: shape, device, datatype, ...) of the input tensor
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3806, 0.9027],
        [0.1579, 0.3980]])


In [5]:
# giving the imput dimetion
shape = (2, 3,)

rand_tensor = torch.rand(shape)
print(rand_tensor)

ones_tensor = torch.ones(shape)
print(ones_tensor)

zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.1050, 0.2412, 0.7552],
        [0.9406, 0.6116, 0.0211]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# some properties of tensor

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operation on Tesors [link](https://pytorch.org/docs/stable/torch.html)

* pytorch by default uses cpu if you want to use gpu you must explicitly do that by method `.to` 
* if the tensor is large and was initialized on cpu moving the large tensors to gpu  could be an overhead over (cpu and memory)

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [8]:
tensor = torch.rand(3, 4, device=device)
# tensor.to(device)
tensor = torch.ones(4, 4, device=device)


#firist raw
print(tensor[0])

#first column
tensor[:, 0] = 0
print(f'\n{tensor} \n {tensor[:, 0]}')
tensor = torch.ones(4, 4)

#last column
tensor[:, -1] = 0
print(f'\n{tensor} \n {tensor[:, -1]}')
tensor = torch.ones(4, 4)


#last column of 3D tensor ->>> three dots '...' means rest of dimetionis
tensor = torch.ones(2, 3, 4)
tensor[..., -1] = 0
print(f'\n{tensor} \n {tensor[..., -1]}')

tensor([1., 1., 1., 1.], device='cuda:0')

tensor([[0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.]], device='cuda:0') 
 tensor([0., 0., 0., 0.], device='cuda:0')

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 
 tensor([0., 0., 0., 0.])

tensor([[[1., 1., 1., 0.],
         [1., 1., 1., 0.],
         [1., 1., 1., 0.]],

        [[1., 1., 1., 0.],
         [1., 1., 1., 0.],
         [1., 1., 1., 0.]]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
#concatination also stacking see: https://pytorch.org/docs/stable/generated/torch.stack.html
tensor = torch.ones(4, 4, device=device)
out_tensor = torch.ones(4, 12, device=device)
torch.cat([tensor, tensor, tensor], dim=-1, out = out_tensor)
out_tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], device='cuda:0')

In [11]:
tensor = torch.ones(4, 4, device=device)
tensor[:, 1] = 0
print(tensor)


#matrix multplication
y1 = tensor @ tensor.T
y2 = torch.matmul(tensor, tensor.T)
torch.matmul(tensor, tensor.T, out=y2)
y3= tensor.matmul(tensor.T)
print(f'\nmatrix multplication \ny1=y2=y3 \n{y1}')


#elemntwise multplication -> smae operation as matpul
z1 = tensor * tensor
z2 = torch.mul(tensor, tensor)
print(f'\nelementwise multplication -> smae operation as matpul \n{z1}')


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')

matrix multplication 
y1=y2=y3 
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], device='cuda:0')

elementwise multplication -> smae operation as matpul 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]], device='cuda:0')


In [12]:
#converting tensor of shpe (1,) to python value
agg = tensor.sum()
print(agg, agg.item())

tensor(12., device='cuda:0') 12.0


In [13]:
# inplace operatins ends with '_' means the ouput will be stored in the same varialble
# CUATION: uing inplae operatoins will omit gradient while backprobagation

tensor = torch.ones(4, 4, device=device)
y = tensor.add(5) # normal

tensor.add_(5) # inplace

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]], device='cuda:0')

# Bridging with numpy

In [18]:
# converting tensor to numpy
tensor = torch.ones(4, device='cpu')
np_tensor = tensor.numpy()
print(f'{tensor}\n{np_tensor}')



#numpy to tensor
np_data = np.ones((2, 2))
tensor = torch.from_numpy(np_data)
print(f'\n{np_data}\n{tensor}')


#change in numpy refleact tensor
np.add(np_data, 4, out=np_data)
print(f'\n{np_data}\n{tensor}')

#change in tensor refleact numpy
torch.add(tensor, 4, out=tensor)
tensor = tensor.add(30) # this will create new varialbe called tensor (it shared no data with the previous tensor)
print(f'\n{np_data}\n{tensor}')

tensor([1., 1., 1., 1.])
[1. 1. 1. 1.]

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

[[5. 5.]
 [5. 5.]]
tensor([[5., 5.],
        [5., 5.]], dtype=torch.float64)

[[9. 9.]
 [9. 9.]]
tensor([[39., 39.],
        [39., 39.]], dtype=torch.float64)
