In [1]:
import torch
import numpy as np

/home/abdullah/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [36]:
softmax = torch.nn.Softmax(dim=1)
pred = torch.tensor([[10,1], [1, 10]], dtype=torch.float)
pred = softmax(pred)
pred

tensor([[9.9988e-01, 1.2339e-04],
        [1.2339e-04, 9.9988e-01]])

In [6]:
label = torch.tensor([1, 0])
label

tensor([1, 0])

In [30]:
weight = torch.tensor([1, 100],dtype=torch.float)
weight

tensor([  1., 100.])

In [31]:
loss = torch.nn.CrossEntropyLoss()
loss_w = torch.nn.CrossEntropyLoss(weight=weight)

In [32]:
loss(pred, label)

tensor(9.0001)

In [33]:
loss_w(pred, label)

tensor(9.0001)